version: "3.1"

services:
  mongo:
    image: mongo
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "27017"
  redis:
    image: redis
    ports:
      - "6379"
  rethink:
    image: rethinkdb
    ports:
      - "8080"
      - "28015"
      - "29015"
  monitoring:
    build: .
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
      RETHINK_HOST: rethink
    ports:
      - "8081:8080"
